spring:
  application:
    name: open-api
  datasource:
    platform: mysql
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:pwd123}
    url: jdbc:mysql://localhost:3306/open_api
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  liquibase:
    change-log: classpath:db/master.xml
    contexts: ${CHANGE_LOG:dev}
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:pwd123}

logging:
  level:
    org.springframework.boot.autoconfigure.liquibase: DEBUG

server:
  port: 8090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
